services:
  backend-quarkus:
    #    image: us-central1-docker.pkg.dev/workout-app-441723/workout-app/spring-backend:latest
    image: backend-quarkus:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    container_name: backend-quarkus
    platform: linux/amd64
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-db
      - SPRING_DATASOURCE_URL=jdbc:postgres://postgres-db:5432/automation
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=LexLuthern246!!??
      - SERVER_PORT=8081
    depends_on:
      - postgres-db
    restart: always
    networks:
      - app-network

  svelte-frontend:
    #    image: us-central1-docker.pkg.dev/workout-app-441723/workout-app/react-frontend:latest
    image: svelte-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-final
    container_name: svelte-frontend
    platform: linux/amd64
    depends_on:
      - backend-quarkus
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    command: ["npm", "run", "preview"]
    restart: always
    networks:
      - app-network
  flask-backend:
    #    image: us-central1-docker.pkg.dev/workout-app-441723/workout-app/react-frontend:latest
    image: flask-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: api-builder
    container_name: flask-backend
    platform: linux/amd64
    depends_on:
      - svelte-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "8082:8082"
    restart: always
    networks:
      - app-network
  postgres-db:
    image: postgres-db:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: postgres-with-backup
    container_name: postgres-db
    environment:
      MYSQL_ROOT_PASSWORD: LexLuthern246!!??
      MYSQL_DATABASE: automation

    ports:
      - "5432:5432"
    #    volumes:
    #      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    #      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge