version: '3.8'

services:
  spring-backend:
    image: spring-backend:latest
    ports:
      - "8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/automation"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "password123"
      SERVER_PORT: "8081"
    networks:
      - app-network

  react-frontend:
    image: react-frontend:latest
    ports:
      - "8080"
    environment:
      NODE_ENV: "production"
    networks:
      - app-network

  python-api:
    image: python-api:latest
    ports:
      - "8082"
    command: ["python", "./recommenderRoute.py"]
    environment:
      DOCKER: "true"
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "LexLuthern246!!??"
      MYSQL_DATABASE: "automation"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data: {}

networks:
  app-network:
    driver: bridge