name: Docker Compose CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_ID: workout-app-441723
  GKE_ZONE: us-central1
  DOCKER_REGISTRY: gcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}

      # Setup Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      # Configure Docker authentication
      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker ${{ env.DOCKER_REGISTRY }} --quiet

      # Build and push images
      - name: Build and Push Docker images
        run: |
          # Build images
          docker compose build
          
          # Tag images
          docker tag spring-backend:latest ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/spring-backend:${{ github.sha }}
          docker tag react-frontend:latest ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/react-frontend:${{ github.sha }}
          docker tag python-api:latest ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/python-api:${{ github.sha }}
          
          # Push images
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/spring-backend:${{ github.sha }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/react-frontend:${{ github.sha }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/python-api:${{ github.sha }}

      # Deploy to Google Cloud
      - name: Deploy to Google Cloud
        run: |
          # Update docker-compose.yml with new image tags
          sed -i "s|spring-backend:latest|${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/spring-backend:${{ github.sha }}|g" docker-compose.yml
          sed -i "s|react-frontend:latest|${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/react-frontend:${{ github.sha }}|g" docker-compose.yml
          sed -i "s|python-api:latest|${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_ID }}/python-api:${{ github.sha }}|g" docker-compose.yml
          
          # Deploy using docker-compose
          docker compose -f docker-compose.yml up -d