name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: workout-app-441723
  GKE_CLUSTER: react-cluster
  GKE_ZONE: us-central1-a
  IMAGE_FRONTEND: react-frontend
  IMAGE_BACKEND: spring-backend

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}  # No quotes
          export_environment_variables: true  # Export credentials to environment variables

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "${{ env.GKE_CLUSTER }}" --zone "${{ env.GKE_ZONE }}" --project "${{ env.PROJECT_ID }}"
    # Configure Docker to use the gcloud command-line tool as a credential helper
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - name: Get GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"
      - name: Clean up old images
        run: |
          gcloud container images list-tags gcr.io/$PROJECT_ID/$IMAGE_FRONTEND --format='get(digest)' --filter='timestamp.datetime < -P7D' | xargs -I {} gcloud container images delete gcr.io/$PROJECT_ID/$IMAGE_FRONTEND@{} --quiet
      # Build the Docker image
      - name: Build Frontend Image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f ./frontend/Dockerfile ./frontend

      - name: Build Backend Image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f ./backend/Dockerfile ./backend

      # Push the Docker image to Google Container Registry
      - name: Push Images to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GITHUB_SHA"

      # Update the image tags in deployment files
      - name: Update Deployment Files
        run: |-
          # Update deployment yaml with new image tags
          sed -i "s|image: gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:.*|image: gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:$GITHUB_SHA|g" k8s-manifest.yaml
          sed -i "s|image: gcr.io/$PROJECT_ID/$IMAGE_BACKEND:.*|image: gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GITHUB_SHA|g" k8s-manifest.yaml

      # Deploy the application to the GKE cluster
      - name: Deploy to GKE
        run: |-
          kubectl apply -f k8s-manifest.yaml

      # Wait for deployment to complete
      - name: Wait for deployments to stabilize
        run: |-
          kubectl rollout status deployment/react-frontend
          kubectl rollout status deployment/spring-backend

      # Output the public IP address
      - name: Get service URLs
        run: |-
          echo "Frontend service available at: $(kubectl get service react-frontend -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"